services:
   app:
      build:
         context: ./Docker-files/app
      image: project1/vproapp
      container_name: vproapp
      ports:
         - "8080:8080"
      volumes:
         - vproappdata:/usr/local/tomcat/webapps
         
   db:
      build:
         context: ./Docker-files/db
      image: project1/vprodb
      container_name: vprodb
      ports:
         - "3306:3306"
      volumes:
         - vprodbdata:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=vprodbpass


   cache:
      image: memcached
      container_name: vprocache01
      ports:
         - "11211:11211"
      

   rmq:
      image: rabbitmq
      container_name : vpromq01
      ports:
         - "5672:5672"
      environment:
         - RABBITMQ_DEFAULT_USER=guest
         - RABBITMQ_DEFAULT_PASS=guest

         
   web:
      build:
         context: ./Docker-files/web
      image: project1/vproweb   
      container_name: vproweb
      ports:
         - "80:80"

volumes:
   vprodbdata: {}
   vproappdata: {}
            
                  